spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080
    jpa:
        hibernate:
            ddl-auto: update #can be update or validate or delete
        show-sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/capstone_products
        username: root
        password: adminroot
        driver-class-name: com.mysql.cj.jdbc.Driver

    application:
        name: Capstone-Product-Service

    url:
        fakeStore:
            specificProduct: "https://fakestoreapi.com/products/{id}"
            product: "https://fakestoreapi.com/products"
    data:
        redis:
            host: localhost
            port: 6379


server:
    port: 9090


#openseach:
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
#    uri: